# Generated by Django 3.2.2 on 2021-05-10 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='my_files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.attachment'),
        ),
    ]
